config/routes.rb
Mousse::Application.routes.draw do
  get 'admin' => "admin#index"
  get 'pageviews' => "admin#pageviews"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :thangs, path: 'reccos'

  get 'about' => 'dashboard#about'

  root 'dashboard#index'
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/thang.rb
class Thang < ActiveRecord::Base
	include FriendlyId

	is_impressionable :counter_cache => true, :column_name => "pageviews"

	friendly_id :what, use: :slugged

  validates :what, :place, :date, :description, presence: true
  validates :what, uniqueness: true
  validates :amount, numericality: { greater_than_or_equal_to: 0.0 }


	def self.active
		where("archived is false")
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  # has_many reccos, dependent: true # looking to the future.


  has_secure_password
  validates_presence_of :password, :on => :create

  after_destroy :ensure_an_admin_remains

  def feed
    # WIP
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy!
  end

  private

  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @time = Time.now
    @thangs = Thang.count
    @users = User.count
  end

	# oh man. this is a nasty, demonic PaaS-tied implementation (:rolleyes:) pay no attention.

	def archive
	  %x[rake archive_old_events]
	end

	def pageviews
		Notifier.send_pageviews_report
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :authorize

  protected

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def authorize
    unless current_user
      redirect_to login_url, notice: "Please log in, dude"
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_before_filter :authorize

  def index
    @thangs = Thang.order(:date)
  end

  def about; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize

  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_url
    else
      redirect_to login_url, alert: "Invalid shit, yo."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged outta here, bitch."
  end
end

app/controllers/thangs_controller.rb
class ThangsController < ApplicationController
  before_action :set_thang, only: [:show, :edit, :update, :destroy]
  skip_before_filter :authorize, only: :show

  # GET /thangs
  # GET /thangs.json
  def index
    @thangs = Thang.all
  end

  # GET /thangs/1
  # GET /thangs/1.json
  def show
		impressionist(@thang)
  end

  # GET /thangs/new
  def new
    @thang = Thang.new
  end

  # GET /thangs/1/edit
  def edit
  end

  # POST /thangs
  # POST /thangs.json
  def create
    @thang = Thang.new(thang_params)

    respond_to do |format|
      if @thang.save
        format.html { redirect_to @thang, notice: 'Thang was successfully created.' }
        format.json { render action: 'show', status: :created, location: @thang }
      else
        format.html { render action: 'new' }
        format.json { render json: @thang.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thangs/1
  # PATCH/PUT /thangs/1.json
  def update
    respond_to do |format|
      if @thang.update(thang_params)
        format.html { redirect_to @thang, notice: 'Thang was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @thang.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thangs/1
  # DELETE /thangs/1.json
  def destroy
    @thang.destroy
    respond_to do |format|
      format.html { redirect_to thangs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thang
      @thang = Thang.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thang_params
      params.require(:thang).permit(:what, :place, :date, :amount, :novelty_rating, :description, :flyer)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully create." }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User #{@user.name} was successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    begin
      @user.destroy
      flash[:notice] = "User #{@user.name} deleted"
    rescue Exception => e
      flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password_digest, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/thangs_helper.rb
module ThangsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div>
  <header>
    <h1>Welcome, bitch.</h1>
  </header>

  <section>
    <p>
      It's <%= @time %>.
    </p>
    <p>
      There are <%= pluralize(@thangs, "thang") %> and <%= pluralize(@users, "user") %>.
    </p>
  </section>

  <section>
    <p><%= link_to "Go to Homepage", root_url %></p>
    
		<h4>Main administrative actions</h4>
		<p><%= link_to "Thang administration", thangs_url %></p>
    <% if current_user.is_admin %>
      <p><%= link_to "User administration", users_url %></p>
    <% end %>

		<h4>Other administrative tasks</h4>
    <p><%= link_to "Send pageviews report", pageviews_url %></p>
	
		<h4>Finale</h4>
    <p><%= link_to "Logoff", logout_url, :method => :delete %></p>
  </section>
</div>

app/views/admin/pageviews.html.erb
¡Email enviado! <%= link_to "Volver", admin_url %>

app/views/dashboard/about.html.erb
<div align="center">
  <iframe width="640" height="360" src="https://www.youtube.com/embed/pdQiSGb4Luw?feature=player_detailpage" frameborder="0" allowfullscreen></iframe><br>
  <%= link_to "Volver", root_url %>

	<div id="about">
		<p>
		  ¡Hola! <strong>Recco</strong> es una herramienta experimental de descubrimiento de actividades culturales.
		</p>
		<p>
			Es inestable y difícilmente funcional, pero está creciendo rápidamente. Espérennos.
		</p>
	</div>
  
	<div id="diskus">
	  <div id="disqus_thread"></div>
	  <script type="text/javascript">
		  var disqus_shortname = 'recco';
      (function() {
     	  var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      	  (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
		  })();
      </script>
    
		  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
		  <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    <div>
</div>

app/views/dashboard/index.html.erb
<div id="container">
  <nav>
    <div class="menu">
      <%= image_tag "logo.png", alt: "loguito", title: "._.·° going out is a timeless desire" %>
      <p><%= link_to "eH... ¿qué es esto?", about_url %></p>
      <p>
        <%- if session[:user_id] -%>
          <%= link_to "salí", logout_url, :method => :delete %>
        <% else %>
          <%= mail_to("airOnGString@gmail.com", "aloha", subject: "SYN", encode: "javascript") %>
        <%- end -%>
      </p>
    </div>
  </nav>
  <div class="stream">
    <% unless @thangs.blank? %>
      <% @thangs.each do |thang| %>
        <div class="unit" >
          <div class="header">
            <% if thang.date.day == DateTime.now.day %>
							<%= link_to thang.what.mb_chars.normalize(:kd).downcase.to_s, thang_path(thang), :class => 'today' %>
            <% else %>
							<%= link_to thang.what.mb_chars.normalize(:kd).downcase.to_s, thang_path(thang) %>
						<% end %>
          </div>
          <div class="details">
            <span>
              <%= thang.place.downcase %>
            </span> |
            <span>
              <%= I18n.localize(thang.date, :format => "%A %d de %B a las %H:%M") %>
            </span>
          </div>
          <p><%= truncate(thang.description, length: 350) %></p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recco</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
	<%= favicon_link_tag 'favicon.ico' %>
</head>
<body>

<%= yield %>

	<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		ga('create', 'UA-43627937-1', 'recco.herokuapp.com');
		ga('send', 'pageview');
	</script>
</body>
</html>

app/views/notifier/send_pageviews_report.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Weekly pageview report from Recco!</h1>
		<table align="center">
			<%- @thangs.each do |thang_title, pageviews| -%>
			<tr>
				<td>
					<%= truncate(thang_title, lenght:15) %>
				</td>
				<td>
					<%= pageviews %> pageviews
				</td>
			</tr>
			<%- end -%>
		</table>
    <p>Have a great day!</p>
		<p>--The nasty folks behind Recco..</p>
  </body>
</html>

app/views/thangs/_form.html.erb
<%= form_for(@thang) do |f| %>
  <% if @thang.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thang.errors.count, "error") %> prohibited this thang from being saved:</h2>

      <ul>
      <% @thang.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :what %><br>
    <%= f.text_field :what %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :novelty_rating %><br>
    <%= f.text_field :novelty_rating %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :flyer %><br>
    <%= f.text_field :flyer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/thangs/edit.html.erb
<h1>Editing thang</h1>

<%= render 'form' %>

<%= link_to 'Show', @thang %> |
<%= link_to 'Back', thangs_path %>

app/views/thangs/index.html.erb
<h1>Listing thangs</h1>

<table>
  <thead>
    <tr>
      <th>What</th>
      <th>Place</th>
      <th>Date</th>
      <th>Amount</th>
      <th>Novelty rating</th>
      <th>Description</th>
      <th>Flyer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @thangs.each do |thang| %>
      <tr>
        <td><%= thang.what %></td>
        <td><%= thang.place %></td>
        <td><%= thang.date %></td>
        <td><%= thang.amount %></td>
        <td><%= thang.novelty_rating %></td>
        <td><%= truncate(thang.description, length: 140) %></td>
        <td><%= thang.flyer %></td>
        <td><%= link_to 'Show', thang %></td>
        <td><%= link_to 'Edit', edit_thang_path(thang) %></td>
        <td><%= link_to 'Destroy', thang, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thang', new_thang_path %>
<%= link_to 'Logoff', logout_path, method: :delete %>

app/views/thangs/new.html.erb
<h1>New thang</h1>

<%= render 'form' %>

<%= link_to 'Back', thangs_path %>

app/views/thangs/show.html.erb
<p>
  <strong>¿Qué?</strong>
  <%= @thang.what %>
</p>

<p>
  <strong>¿Dónde?</strong>
  <%= @thang.place %>
</p>

<p>
  <strong>¿Cuando?</strong>
  <%= @thang.date.in_time_zone("Buenos Aires") %>
</p>

<p>
  <strong>¿Cuánto decís?</strong>
	<% amount = (@thang.amount == 0) ? "Gratis." : "#{@thang.amount.to_i} pesos." %>
  <%= amount %>
</p>

<p>
  <strong>Descripción</strong>
  <%= @thang.description %>
</p>

<p>
	<% if session[:user_id] %>
  	<%= link_to 'Edit', edit_thang_path(@thang) %> |
  	<%= link_to 'Back', thangs_path %>
	<% else %>
  	<%= link_to 'Atrás', root_path %>
	<% end %>
</p>
<div id="diskus">
	<div id="disqus_thread"></div>
	<script type="text/javascript">
		var disqus_shortname = 'recco'; // required: replace example with your forum shortname

    (function() {
    	var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      	(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
		})();
    </script>
    
		<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
		<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
<div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Enter User details:</legend>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password, size: 40 %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation, size: 40 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
<% end %>

<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <% if current_user.is_admin %>
        <th></th>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <% if current_user.is_admin %>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.is_admin %>
  <td><%= link_to 'New User', new_user_path %></p>
<% end %>

<%= link_to 'Logoff', logout_path, method: :delete %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>